<?php

namespace App\Tests\Security;

use App\Entity\User;
use App\Security\Voter\UserVoter;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Authorization\Voter\VoterInterface;

final class UserVoterTest extends TestCase
{
    public function testAdminCanAccessAnyUser(): void
    {
        $admin = $this->userWithId(1, ['ROLE_ADMIN']);
        $target = $this->userWithId(2);

        self::assertSame(
            VoterInterface::ACCESS_GRANTED,
            (new UserVoter())->vote($this->tokenFor($admin), $target, [UserVoter::EDIT]),
        );
    }

    public function testOwnerCanAccessOwnUserRecord(): void
    {
        $owner = $this->userWithId(10);
        $target = $this->userWithId(10);

        self::assertSame(
            VoterInterface::ACCESS_GRANTED,
            (new UserVoter())->vote($this->tokenFor($owner), $target, [UserVoter::VIEW]),
        );
    }

    public function testDifferentUserIsDenied(): void
    {
        $current = $this->userWithId(10);
        $target = $this->userWithId(11);

        self::assertSame(
            VoterInterface::ACCESS_DENIED,
            (new UserVoter())->vote($this->tokenFor($current), $target, [UserVoter::DELETE]),
        );
    }

    private function tokenFor(User $user): TokenInterface
    {
        $token = $this->createStub(TokenInterface::class);
        $token->method('getUser')->willReturn($user);

        return $token;
    }

    /**
     * Entity IDs are generated by Doctrine; reflection keeps the voter test unit-level.
     */
    private function userWithId(int $id, array $roles = ['ROLE_USER']): User
    {
        $user = (new User())
            ->setEmail(sprintf('user-%d@example.test', $id))
            ->setPassword('')
            ->setRoles($roles);

        $property = new \ReflectionProperty(User::class, 'id');
        $property->setValue($user, $id);

        return $user;
    }
}
