<?php

namespace ContainerAu4364x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserRegistrationProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\UserRegistrationProcessor' shared autowired service.
     *
     * @return \App\State\UserRegistrationProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'state'.\DIRECTORY_SEPARATOR.'ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'State'.\DIRECTORY_SEPARATOR.'UserRegistrationProcessor.php';

        return $container->privates['App\\State\\UserRegistrationProcessor'] = new \App\State\UserRegistrationProcessor(($container->privates['api_platform.doctrine.orm.state.persist_processor'] ?? $container->load('getApiPlatform_Doctrine_Orm_State_PersistProcessorService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Service\\EmailVerifier'] ?? $container->load('getEmailVerifierService')));
    }
}
