<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260507111500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add chatbot conversation history.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE chatbot_conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, transcript TEXT DEFAULT NULL, locale VARCHAR(10) DEFAULT 'fr' NOT NULL, escalated BOOLEAN DEFAULT false NOT NULL, handled BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE chatbot_conversation');
    }
}
