<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY1yOalY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY1yOalY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY1yOalY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY1yOalY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY1yOalY\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y1yOalY',
    'container.build_id' => 'fc7c8437',
    'container.build_time' => 1774514228,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY1yOalY');
