<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXNbUSgS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXNbUSgS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXNbUSgS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXNbUSgS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXNbUSgS\App_KernelDevDebugContainer([
    'container.build_hash' => 'XNbUSgS',
    'container.build_id' => '3c763cc8',
    'container.build_time' => 1779132380,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXNbUSgS');
