<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App_Entity_Address' => 0,
'App_Entity_User' => 1,
'Symfony_Component_Security_Core_User_UserInterface' => 2,
'Symfony_Component_Security_Core_User_PasswordAuthenticatedUserInterface' => 3,
'App_Entity_Order' => 4,
'App_Entity_CarouselSlide' => 5,
'App_Entity_Cart' => 6,
'App_Entity_PromoCode' => 7,
'App_Entity_CartItem' => 8,
'App_Entity_SaasService' => 9,
'App_Entity_Category' => 10,
'App_Entity_ContactMessage' => 11,
'App_Entity_HomepageText' => 12,
'App_Entity_Invoice' => 13,
'App_Entity_OrderItem' => 14,
'App_Entity_PaymentMethod' => 15,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Address',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'firstname' => $o[2],
                    'lastname' => $o[3],
                    'adresse1' => $o[4],
                    'adresse2' => $o[5],
                    'city' => $o[6],
                    'region' => $o[7],
                    'zipCode' => $o[8],
                    'country' => $o[9],
                    'mobilephone' => $o[10],
                    'user' => $o[11],
                    'orders' => $o[12],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'firstname',
                'lastname',
                'adresse1',
                'adresse2',
                'city',
                'region',
                'zipCode',
                'country',
                'mobilephone',
                'user',
                'orders',
            ],
            'groups' => [
                1 => [
                    'address:read',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                    'order:read',
                ],
                [
                    'address:read',
                    'address:write',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\User',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'email' => $o[2],
                    'roles' => $o[3],
                    'password' => $o[4],
                    'plainPassword' => $o[5],
                    'firstname' => $o[6],
                    'lastname' => $o[7],
                    'isVerified' => $o[8],
                    'emailVerificationToken' => $o[9],
                    'emailVerificationSentAt' => $o[10],
                    'passwordResetToken' => $o[11],
                    'passwordResetExpiresAt' => $o[12],
                    'totpSecret' => $o[13],
                    'totpEnabled' => $o[14],
                    'createdAt' => $o[15],
                    'addresses' => $o[16],
                    'orders' => $o[17],
                    'userIdentifier' => $o[18],
                    'verified' => $o[19],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'email',
                'roles',
                'password',
                'plainPassword',
                'firstname',
                'lastname',
                'isVerified',
                'emailVerificationToken',
                'emailVerificationSentAt',
                'passwordResetToken',
                'passwordResetExpiresAt',
                'totpSecret',
                'totpEnabled',
                'createdAt',
                'addresses',
                'orders',
                'userIdentifier',
                'verified',
            ],
            'groups' => [
                1 => [
                    'user:read',
                    'order:read',
                ],
                [
                    'user:read',
                    'user:write',
                    'order:read',
                ],
                [
                    'user:read',
                ],
                5 => [
                    'user:write',
                ],
                [
                    'user:read',
                    'user:write',
                    'order:read',
                ],
                [
                    'user:read',
                    'user:write',
                    'order:read',
                ],
                [
                    'user:read',
                ],
                14 => [
                    'user:read',
                ],
                [
                    'user:read',
                ],
                [
                    'user:read',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'Symfony\\Component\\Security\\Core\\User\\UserInterface',
            ],
            'attributesMetadata' => [
                [
                    'roles' => $o[1],
                    'userIdentifier' => $o[2],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'roles',
                'userIdentifier',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface',
            ],
            'attributesMetadata' => [
                [
                    'password' => $o[1],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'password',
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Order',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'reference' => $o[2],
                    'totalPrice' => $o[3],
                    'status' => $o[4],
                    'createdAt' => $o[5],
                    'paidAt' => $o[6],
                    'user' => $o[7],
                    'billingAddress' => $o[8],
                    'items' => $o[9],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'reference',
                'totalPrice',
                'status',
                'createdAt',
                'paidAt',
                'user',
                'billingAddress',
                'items',
            ],
            'groups' => [
                1 => [
                    'order:read',
                ],
                [
                    'order:read',
                ],
                [
                    'order:read',
                ],
                [
                    'order:read',
                ],
                [
                    'order:read',
                ],
                [
                    'order:read',
                ],
                [
                    'order:read',
                ],
                [
                    'order:read',
                    'order:write',
                ],
                [
                    'order:read',
                    'order:write',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\CarouselSlide',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'title' => $o[2],
                    'subtitle' => $o[3],
                    'image' => $o[4],
                    'linkUrl' => $o[5],
                    'ctaLabel' => $o[6],
                    'displayOrder' => $o[7],
                    'active' => $o[8],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'title',
                'subtitle',
                'image',
                'linkUrl',
                'ctaLabel',
                'displayOrder',
                'active',
            ],
            'groups' => [
                1 => [
                    'carousel:read',
                ],
                [
                    'carousel:read',
                    'carousel:write',
                ],
                [
                    'carousel:read',
                    'carousel:write',
                ],
                [
                    'carousel:read',
                    'carousel:write',
                ],
                [
                    'carousel:read',
                    'carousel:write',
                ],
                [
                    'carousel:read',
                    'carousel:write',
                ],
                [
                    'carousel:read',
                    'carousel:write',
                ],
                [
                    'carousel:read',
                    'carousel:write',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Cart',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'token' => $o[2],
                    'user' => $o[3],
                    'promoCode' => $o[4],
                    'createdAt' => $o[5],
                    'updatedAt' => $o[6],
                    'items' => $o[7],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'token',
                'user',
                'promoCode',
                'createdAt',
                'updatedAt',
                'items',
            ],
            'groups' => [
                1 => [
                    'cart:read',
                ],
                [
                    'cart:read',
                ],
                [
                    'cart:read',
                ],
                [
                    'cart:read',
                    'cart:write',
                ],
                [
                    'cart:read',
                ],
                [
                    'cart:read',
                ],
                [
                    'cart:read',
                    'cart:write',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
7 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\PromoCode',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'code' => $o[2],
                    'percentage' => $o[3],
                    'startsAt' => $o[4],
                    'endsAt' => $o[5],
                    'active' => $o[6],
                    'maxUsages' => $o[7],
                    'usageCount' => $o[8],
                    'usable' => $o[9],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'code',
                'percentage',
                'startsAt',
                'endsAt',
                'active',
                'maxUsages',
                'usageCount',
                'usable',
            ],
            'groups' => [
                1 => [
                    'promo_code:read',
                ],
                [
                    'promo_code:read',
                    'promo_code:write',
                ],
                [
                    'promo_code:read',
                    'promo_code:write',
                ],
                [
                    'promo_code:read',
                    'promo_code:write',
                ],
                [
                    'promo_code:read',
                    'promo_code:write',
                ],
                [
                    'promo_code:read',
                    'promo_code:write',
                ],
                [
                    'promo_code:read',
                    'promo_code:write',
                ],
                [
                    'promo_code:read',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
8 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\CartItem',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'cart' => $o[2],
                    'saasService' => $o[3],
                    'quantity' => $o[4],
                    'durationMonths' => $o[5],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'cart',
                'saasService',
                'quantity',
                'durationMonths',
            ],
            'groups' => [
                1 => [
                    'cart:read',
                    'cart_item:read',
                ],
                [
                    'cart_item:read',
                    'cart_item:write',
                ],
                [
                    'cart:read',
                    'cart_item:read',
                    'cart_item:write',
                ],
                [
                    'cart:read',
                    'cart:write',
                    'cart_item:read',
                    'cart_item:write',
                ],
                [
                    'cart:read',
                    'cart:write',
                    'cart_item:read',
                    'cart_item:write',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
9 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\SaasService',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'description' => $o[3],
                    'technicalSpecs' => $o[4],
                    'price' => $o[5],
                    'isAvailable' => $o[6],
                    'priority' => $o[7],
                    'image' => $o[8],
                    'category' => $o[9],
                    'available' => $o[10],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'name',
                'description',
                'technicalSpecs',
                'price',
                'isAvailable',
                'priority',
                'image',
                'category',
                'available',
            ],
            'groups' => [
                1 => [
                    'saas_service:read',
                    'category:read',
                    'order:read',
                    'order_item:read',
                ],
                [
                    'saas_service:read',
                    'saas_service:write',
                    'category:read',
                    'order:read',
                    'order_item:read',
                ],
                [
                    'saas_service:read',
                    'saas_service:write',
                    'category:read',
                ],
                [
                    'saas_service:read',
                    'saas_service:write',
                    'category:read',
                ],
                [
                    'saas_service:read',
                    'saas_service:write',
                    'category:read',
                    'order:read',
                    'order_item:read',
                ],
                [
                    'saas_service:read',
                    'saas_service:write',
                    'category:read',
                ],
                [
                    'saas_service:read',
                    'saas_service:write',
                    'category:read',
                ],
                [
                    'saas_service:read',
                    'saas_service:write',
                    'category:read',
                ],
                [
                    'saas_service:read',
                    'saas_service:write',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
10 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Category',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'image' => $o[3],
                    'displayOrder' => $o[4],
                    'saasServices' => $o[5],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'name',
                'image',
                'displayOrder',
                'saasServices',
            ],
            'groups' => [
                1 => [
                    'category:read',
                    'saas_service:read',
                ],
                [
                    'category:read',
                    'category:write',
                    'saas_service:read',
                ],
                [
                    'category:read',
                    'category:write',
                ],
                [
                    'category:read',
                    'category:write',
                ],
                [
                    'category:read',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
11 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\ContactMessage',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'fullName' => $o[2],
                    'email' => $o[3],
                    'subject' => $o[4],
                    'message' => $o[5],
                    'handled' => $o[6],
                    'createdAt' => $o[7],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'fullName',
                'email',
                'subject',
                'message',
                'handled',
                'createdAt',
            ],
            'groups' => [
                1 => [
                    'contact:read',
                ],
                [
                    'contact:read',
                    'contact:write',
                ],
                [
                    'contact:read',
                    'contact:write',
                ],
                [
                    'contact:read',
                    'contact:write',
                ],
                [
                    'contact:read',
                    'contact:write',
                ],
                [
                    'contact:read',
                ],
                [
                    'contact:read',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
12 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\HomepageText',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'slug' => $o[2],
                    'title' => $o[3],
                    'body' => $o[4],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'slug',
                'title',
                'body',
            ],
            'groups' => [
                1 => [
                    'homepage_text:read',
                ],
                [
                    'homepage_text:read',
                    'homepage_text:write',
                ],
                [
                    'homepage_text:read',
                    'homepage_text:write',
                ],
                [
                    'homepage_text:read',
                    'homepage_text:write',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
13 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Invoice',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'number' => $o[2],
                    'order' => $o[3],
                    'totalAmount' => $o[4],
                    'taxAmount' => $o[5],
                    'pdfPath' => $o[6],
                    'issuedAt' => $o[7],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'number',
                'order',
                'totalAmount',
                'taxAmount',
                'pdfPath',
                'issuedAt',
            ],
            'groups' => [
                1 => [
                    'invoice:read',
                ],
                [
                    'invoice:read',
                ],
                [
                    'invoice:read',
                ],
                [
                    'invoice:read',
                ],
                [
                    'invoice:read',
                ],
                [
                    'invoice:read',
                ],
                [
                    'invoice:read',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
14 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\OrderItem',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'order' => $o[2],
                    'saasService' => $o[3],
                    'productNameSnapshot' => $o[4],
                    'unitPriceSnapshot' => $o[5],
                    'quantity' => $o[6],
                    'durationMonths' => $o[7],
                    'subscriptionStartsAt' => $o[8],
                    'subscriptionEndsAt' => $o[9],
                    'subscriptionStatus' => $o[10],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'order',
                'saasService',
                'productNameSnapshot',
                'unitPriceSnapshot',
                'quantity',
                'durationMonths',
                'subscriptionStartsAt',
                'subscriptionEndsAt',
                'subscriptionStatus',
            ],
            'groups' => [
                1 => [
                    'order:read',
                    'order_item:read',
                ],
                3 => [
                    'order:read',
                    'order:write',
                    'order_item:read',
                    'order_item:write',
                ],
                [
                    'order:read',
                    'order_item:read',
                ],
                [
                    'order:read',
                    'order_item:read',
                ],
                [
                    'order:read',
                    'order:write',
                    'order_item:read',
                    'order_item:write',
                ],
                [
                    'order:read',
                    'order:write',
                    'order_item:read',
                    'order_item:write',
                ],
                [
                    'order:read',
                    'order_item:read',
                ],
                [
                    'order:read',
                    'order_item:read',
                ],
                [
                    'order:read',
                    'order_item:read',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },
15 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\PaymentMethod',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'user' => $o[2],
                    'providerToken' => $o[3],
                    'provider' => $o[4],
                    'brand' => $o[5],
                    'last4' => $o[6],
                    'expMonth' => $o[7],
                    'expYear' => $o[8],
                    'isDefault' => $o[9],
                    'default' => $o[10],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'user',
                'providerToken',
                'provider',
                'brand',
                'last4',
                'expMonth',
                'expYear',
                'isDefault',
                'default',
            ],
            'groups' => [
                1 => [
                    'payment_method:read',
                ],
                4 => [
                    'payment_method:read',
                    'payment_method:write',
                ],
                [
                    'payment_method:read',
                    'payment_method:write',
                ],
                [
                    'payment_method:read',
                    'payment_method:write',
                ],
                [
                    'payment_method:read',
                    'payment_method:write',
                ],
                [
                    'payment_method:read',
                    'payment_method:write',
                ],
                [
                    'payment_method:read',
                    'payment_method:write',
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
